### ISSUE TITLE
CIが通らない

### ISSUE THREAD

**Issue by NaokiHamada** [opthub-org/problem-machine-scheduling#3]
testsのインポートパスの問題
Pythonパスのルートはgitのルートディレクトリにしたい。

**Comment by NaokiHamada** [comment]
@TakatoKinoshita 相対インポートがうまく解決できないです

テストはどのカレントディレクトリから、どんなコマンドで実行していますか？

**Comment by TakatoKinoshita** [comment]
すいませんこれは完全に僕が変な構成で運用してたのが悪いです．  
絶対インポートに直します

**Comment by TakatoKinoshita** [comment]
@NaokiHamada PR #5 CI通りました
