### ISSUE TITLE
出力の形式

### ISSUE THREAD

**Issue by TakatoKinoshita** [opthub-org/problem-machine-scheduling#4]
現状:
https://github.com/opthub-org/machine-scheduling/blob/0325e18bc46e82a37a4243ca421a95aa3e18fbe9/problem.py#L183-L190

MTGメモ:
```json
{
  "objective": float,
  "constraint": [float],
  "error": str,
  "info": "n sec"
}
```

**Comment by NaokiHamada** [comment]
現状でOKだと思います。
