### ISSUE TITLE
CIをunittestに直す

### ISSUE THREAD

**Issue by TakatoKinoshita** [opthub-org/problem-machine-scheduling#6]
https://github.com/opthub-org/machine-scheduling/blob/0325e18bc46e82a37a4243ca421a95aa3e18fbe9/.github/workflows/python-package-conda.yml#L34

現状標準ライブラリのunittestを使っている．pytestに移行すべき？
https://github.com/opthub-org/machine-scheduling/blob/0325e18bc46e82a37a4243ca421a95aa3e18fbe9/tests/test_problem.py#L1

**Comment by NaokiHamada** [comment]
unittestのままでいいですよ。
CIファイルがデフォルトでpytestだったので、そのまま使っただけです。
CI側を直しましょう。
