### ISSUE TITLE
入力のプロパティを過不足なく要求するようにする

### ISSUE THREAD

**Issue by TakatoKinoshita** [opthub-org/problem-machine-scheduling#7]
現状は許容
https://github.com/opthub-org/machine-scheduling/blob/0325e18bc46e82a37a4243ca421a95aa3e18fbe9/tests/test_problem.py#L66-L75

**Comment by NaokiHamada** [comment]
関係ないプロパティは許容しないようにしてください（許容すると、巨大なフィールドを送り付けることができるなどのセキュリティホールになるので）。
また、`var`と`timeout`は必須にしておいてください。
```json
{
    "type": "object",
    "properties": {
        … 略 …
    },
    "additionalProperties": false, # 余分なキーの追加は禁止
    "required": ["var", "timeout"]    # varキーとtimeoutキーは必須
} 
```

**Comment by TakatoKinoshita** [comment]
>  また、varとtimeoutは必須にしておいてください。

現状相当するテストケースを用意はしてあります．
https://github.com/opthub-org/machine-scheduling/blob/73df4163c01ab303e34323407a28a3de059d06ed/tests/test_problem.py#L141-L158
よく見ると，`var`が足りないケースが不足している気がしますが...

**Comment by TakatoKinoshita** [comment]
これもテストから手を付けるべき
